#!/bin/bash
$HOME/.config/bspwm/autostart
$HOME/.config/bspwm/theme

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"


bspc rule -a firefox desktop='^2'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a code-oss desktop='^4'
bspc rule -a libreoffice desktop='^5'
bspc rule -a libreoffice-startcenter desktop='^5'

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
